# Generated by Django 2.2.7 on 2019-11-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksSingleView', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='song',
            new_name='musicalWork',
        ),
    ]
